version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
